/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tomkel.advent;

public class App {

    public static void main(String[] args) {

        try {
            Runner.main(args);
        } catch (ClassNotFoundException ex) {
            throw new RuntimeException(ex);
        }
    }
}
